name: Terraform AWS Deploy

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:

    - name: step 1 - Get Code
      uses: actions/checkout@v4

    - name: step 2 - Connect AWS
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Setup 3 - Setup Terraform
      uses: hashicorp/setup-terraform@v2   

    - name:  Step - 4 Terraform Init
      run: terraform init

    - name:  Step - 5 Terraform Validate
      run: terraform validate

    - name:  Step - 6 Terraform Plan
      run: terraform plan

    - name:  Step - 7 Terraform Apply
      run: terraform apply -auto-approve

    - name: Step - 8 Print EC2 IP
      run: |
        EC2_IP=$(terraform output -raw ec2_public_ip)
         echo "My Server IP: $EC2_IP ✅"
