name: Terraform AWS Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2

jobs:

  # JOB 1 - INFRASTRUCTURE
  infrastructure:

    runs-on: ubuntu-latest

    outputs:
      ec2_ip: ${{ steps.get_ip.outputs.ec2_ip }}

    steps:

      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get EC2 Public IP
        id: get_ip
        run: |
          EC2_IP=$(terraform output -raw ec2_public_ip)
          echo "ec2_ip=$EC2_IP" >> $GITHUB_OUTPUT

      - name: Print Website URL
        run: |
          echo "=============================="
          echo "🌐 Website: http://${{ steps.get_ip.outputs.ec2_ip }}"
          echo "=============================="

  # JOB 2 - CHECK WEBSITE
  check:

    runs-on: ubuntu-latest

    needs: infrastructure

    steps:

      - name: Wait for Website
        run: sleep 60

      - name: Check Website
        run: |
          EC2_IP=${{ needs.infrastructure.outputs.ec2_ip }}

          echo "Checking website... ⏳"

          curl -I http://$EC2_IP

          echo "Website is UP! ✅"

  # JOB 3 - NOTIFY
  notify:

    runs-on: ubuntu-latest

    needs: check

    if: always()

    steps:

      - name: Notify Success
        if: success()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK }} \
          -H 'Content-type: application/json' \
          --data '{"text":"✅ Website Deployed Successfully 🚀"}'

      - name: Notify Failure
        if: failure()
        run: |
          curl -X POST ${{ secrets.SLACK_WEBHOOK }} \
          -H 'Content-type: application/json' \
          --data '{"text":"❌ Deployment Failed"}'

  # JOB 4 - CLEANUP
  cleanup:

    runs-on: ubuntu-latest

    needs: notify

    steps:

      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Wait 5 Minutes
        run: |
          echo "Waiting 5 minutes ⏳"
          sleep 300

      - name: Delete Infrastructure
        run: terraform destroy -auto-approve

      - name: Done
        run: echo "💰 EC2 Deleted! Money Saved!"