name: Deploy First Pipeline

on:
  push:
    branches: [main]

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "hello sagar"

      - name: Check System
        run: uname -a

      - name: Check Node Version
        run: node --version

      - name: Check Python Version
        run: python3 --version

      - name: Check Disk Space
        run: df -h

      - name: Create a File
        run: echo "this side from sagar" > file.txt

      - name: Read the File
        run: cat file.txt

      - name: Show All Files
        run: ls -la
