name: Deploy First Pipeline

on:
  push:
    branches: [main]

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
           node-version: 18

      - name: Install Dependencies
        run: npm install


      - name: Run Tests
        run: npm test

      - name: Show Installed Packages
        run: ls node_modules
