name: Deploy First Pipeline

on:
  push:
    branches: [main]

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v4

      - name: See My Files
        run: ls 

      - name: See My Code
        run: cat .github/workflows/main.yml


      - name: Show Current Folder
        run: pwd 

      - name: Show All Files Detail
        run: ls -la
